version: '2.2'
services:

  file_backup:
    image: nikashitsa/file-backup
    mem_limit: 50mb # perhaps you need to increase this limit
    cpus: 0.5 # 50%
    volumes:
      - /path/to/your/files:/data
      - /file-backup/cache:/root/.cache/duplicity
    environment:
      REMOTE_URL: 's3://s3.eu-central-1.amazonaws.com/file-backup/my-files'
      PARAMS: '--volsize=200 --s3-multipart-chunk-size=100 --full-if-older-than=7D'
      BACKUP_LIFETIME: '30D' # remove old (30 days) backups. Remove this line to keep all backups
      BACKUP_TIME: '0 3 * * *' # once per day.
      AWS_ACCESS_KEY_ID: 'put your value here'
      AWS_SECRET_ACCESS_KEY: 'put your value here'
      TELEGRAM_TOKEN: 'put your value here' # optional
      TELEGRAM_CHAT_ID: 'put your value here' # optional
    logging:
      options:
        max-size: '10m'
        max-file: '5'
