version: '2.2'
services:

  file_backup:
    build: .
    mem_limit: 50mb
    cpus: 0.5
    volumes:
      - ./your_files:/data
      - ./cache:/root/.cache/duplicity
    environment:
      REMOTE_URL: ''
      PARAMS: ''
      BACKUP_LIFETIME: ''
      BACKUP_TIME: ''
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
      TELEGRAM_TOKEN: ''
      TELEGRAM_CHAT_ID: ''
    logging:
      options:
        max-size: '10m'
        max-file: '5'
